services:
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      - KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
    networks:
      - spring-demo
    command:
      - "start-dev"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-app-bsn
    ports:
      - "8080:8080"
    environment:
      - DB_URL=$DB_URL
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    networks:
      - spring-demo
    depends_on:
      - keycloak
    restart: unless-stopped
networks:
  spring-demo:
    driver: bridge

volumes:
  keycloak:
    driver: local